### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by phlummox** [spacejam/tla-rust#1]
The README says " ...c form uses braces and p form uses prolog/ruby-esque begin and end statements that can be a little easier to spot errors with, in my opinion".  
  I assume "prolog" is a typo, and you meant Algol, or Pascal, or Ada? Since prolog has no concept of blocks. Cheers

**Comment by spacejam** [comment]
Thanks for catching this! The p-form manual describes it as "the prolix form" which my mind must have corrupted into prolog upon recall. Fixed!
